# Generated by Django 4.2.4 on 2023-08-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=50)),
                ('cnpj', models.IntegerField()),
                ('endereco', models.TextField(max_length=150)),
            ],
        ),
    ]
