# Generated by Django 4.2.4 on 2024-01-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.IntegerField(unique=True),
        ),
    ]
