# Generated by Django 4.2.4 on 2024-12-15 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0004_material_preco_m2'),
        ('Estoque', '0002_movimentacaodeestoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='materiais.material'),
        ),
    ]
