# Generated by Django 4.2.4 on 2023-08-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.IntegerField(max_length=11)),
                ('endereco', models.TextField(max_length=150)),
                ('data_nascimento', models.CharField(max_length=13, null=True)),
                ('email', models.EmailField(max_length=150)),
            ],
        ),
    ]
