# Generated by Django 4.2.4 on 2023-08-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_ciente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciente',
            name='data_nascimento',
            field=models.DateField(),
        ),
    ]
