# Generated by Django 4.2.4 on 2023-08-24 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_ciente_data_nascimento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ciente',
            new_name='Cliente',
        ),
    ]
