# Generated by Django 4.2.4 on 2024-02-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0002_alter_peca_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peca',
            name='dimensoes',
        ),
        migrations.AddField(
            model_name='peca',
            name='descrição',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='peca',
            name='quantidade_metros',
            field=models.FloatField(null=True),
        ),
    ]
