# Generated by Django 4.2.4 on 2023-12-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0002_material_fornecedor'),
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='materiais',
            field=models.ManyToManyField(to='materiais.material'),
        ),
    ]
