# Generated by Django 4.2.4 on 2024-01-23 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_orcamento_materiais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamento',
            old_name='materiais',
            new_name='material',
        ),
    ]
