# Generated by Django 4.2.4 on 2024-03-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0004_alter_peca_descrição'),
        ('orcamentos', '0003_rename_materiais_orcamento_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='material',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='pecas',
            field=models.ManyToManyField(to='pecas.peca'),
        ),
    ]
