# Generated by Django 4.2.4 on 2025-02-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0005_alter_orcamento_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
