# Generated by Django 4.2.4 on 2024-12-16 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_venda_orcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
