# Generated by Django 4.2.4 on 2023-08-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=15)),
                ('cpf', models.TextField(max_length=11)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
