# Generated by Django 4.2.5 on 2023-09-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
