# Generated by Django 4.2.4 on 2024-07-07 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0005_alter_colaborador_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='cargo',
        ),
    ]
