# Generated by Django 4.2.4 on 2023-08-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='fornecedor',
            field=models.ManyToManyField(to='fornecedores.fornecedor'),
        ),
    ]
