# Generated by Django 4.2.4 on 2024-01-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0002_material_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
